version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build_unittest:
    executor:
      name: python/default
      tag: '3.9.1'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: test
          command: |
            python -m junitxml.main -s src -p *_test.py
      - store_test_results:
          path: junit.xml
workflows:
  main:
    jobs:
      - build_unittest
      - python/test:
          test-tool: pytest
          test-tool-args: '--junitxml=test-report/pytest.xml'
          version: '3.9.1'
