version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - run:
          command: 'python -m junitxml.main -s src -p *_test.py'
      - store_test_results
workflows:
  main:
    jobs:
      - build
