version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum ".python-version" }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip
      - save_cache:
          key: dependency-cache-{{ checksum ".python-version" }}-{{ checksum "requirements.txt" }}
          paths:
            - .cache
      - run:
          name: Test
          command: |
            python -m unittest -d src
      - store_test_results:
          path: ./test_output

workflows:
  version: 2
  test:
    jobs:
      - test
